service_install_run_data_source_connection: "jdbc:mysql://mysql_8_0_33:3306/{{env}}?createDatabaseIfNotExist=true"
service_install_run_data_source_connection_user: "root"
service_install_run_data_source_connection_password: "password"
service_install_run_data_connection_user: "root"
service_install_run_data_connection_password: "password"
service_install_run_data_connection: "mongodb://mongo:27017/{{env}}"

service_install_run_registry_url: "https://192.168.5.5:5000"
service_install_run_registry_user: "ahmeddhibi"
service_install_run_registry_password: "password"


service_install_run_image: "192.168.5.5:5000/eduhousing:0.0.1-SNAPSHOT-c3c1bdd"
service_install_run_version: "0.0.1-SNAPSHOT"

